<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
	<xsl:output omit-xml-declaration="yes" indent="no" method="text" encoding="UTF-8"/>
	<xsl:template match="/">
		<xsl:text>/************************************************************************
This class is generated by ZrXSCodeGen
ZrXSCodeGen </xsl:text>
		<xsl:value-of select="entity/@XSCodeGen"/>
		<xsl:text>
Aspx v 0.2 2006-05-28
*************************************************************************/
using System;

namespace </xsl:text>
		<xsl:value-of select="entity/@namespace"/>
		<xsl:text>.Model
{
</xsl:text>
		<xsl:apply-templates select="entity"/>
		<xsl:text>
}
</xsl:text>
	</xsl:template>
	<xsl:template match="entity">
	/// &lt;summary&gt;
	/// <xsl:value-of select="@name"/> is an entity class that represents <xsl:value-of select="@description"/>
	/// &lt;/summary&gt;
	[Serializable]
	public class <xsl:value-of select="@modelName"/>
	{
		#region declaration
		&lt;tr&gt;
	        &lt;td class='category' style="width:140px">
                Add <xsl:value-of select="@name"/>&lt;/td&gt;
	        &lt;td class='category'&gt;&lt;/td&gt;
        &lt;/tr&gt;<xsl:for-each select="./columns/property">
		&lt;tr&gt;
        	&lt;td><xsl:value-of select="@name"/>&lt;/td&gt;
        	&lt;td align="left"&gt;
        		&lt;asp:TextBox id="txt<xsl:value-of select="@name"/>" MaxLength="<xsl:value-of select="@sqlLength"/>" Width="300" runat="server"&gt;&lt;/asp:TextBox&gt;
        	&lt;/td&gt;
        &lt;/tr&gt;</xsl:for-each>
        &lt;tr&gt;
            &lt;td>&lt;/td>
            &lt;td align="left">
            	&lt;asp:Button id="btnAdd" runat="server" Text="Add" onclick="btnAdd_Click">&lt;/asp:Button>
            &lt;/td>
        &lt;/tr&gt;
		#endregion
		
		#region constructors
		/// &lt;summary&gt;
        /// Default constructor
        /// &lt;/summary&gt;
		public <xsl:value-of select="@modelName"/>() { }
		
		/// &lt;summary&gt;
        /// Full constructor
        /// &lt;/summary&gt;
		public <xsl:value-of select="@modelName"/>(<xsl:for-each select="./columns/property">
			<xsl:value-of select="@type"/>
			<xsl:text> </xsl:text>
			<xsl:value-of select="@lowerName"/>			
			<xsl:if test="position()!=last()">
				<xsl:text>, </xsl:text>
			</xsl:if>
		</xsl:for-each>)
        {<xsl:for-each select="./columns/property">
			this.<xsl:value-of select="@field"/> = <xsl:value-of select="@lowerName"/>
			<xsl:text>;</xsl:text>
		</xsl:for-each>
        }        
		#endregion

		#region property<xsl:for-each select="./columns/property">
		/// &lt;summary&gt;
		/// <xsl:value-of select="@name"/>
			<xsl:text> is a </xsl:text>
			<xsl:value-of select="@type"/>
			<xsl:text> property that represents </xsl:text>
			<xsl:value-of select="@description"/>
		/// &lt;/summary&gt;
		public <xsl:value-of select="@type"/><xsl:text> </xsl:text>
			<xsl:value-of select="@name"/>
		{
			get	{ return <xsl:value-of select="@field"/>; }
			set	{ <xsl:value-of select="@field"/> = value; }
		}</xsl:for-each>
		#endregion		
	}</xsl:template>
</xsl:stylesheet>