<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
	<xsl:output omit-xml-declaration="yes" indent="no" method="text" encoding="UTF-8"/>
	<xsl:template match="/">
		<xsl:text>/************************************************************************
This class is generated by ZrXSCodeGen
ZrXSCodeGen </xsl:text>
		<xsl:value-of select="entity/@XSCodeGen"/>
		<xsl:text>
DAL
*************************************************************************/
using System;
using System.Text;
using System.Collections.Generic;
using System.Data.SqlClient;

using SouEi.Model;
using SouEi.DBUtility;

namespace </xsl:text>
		<xsl:value-of select="entity/@namespace"/>
		<xsl:text>.DAL
{
</xsl:text>
		<xsl:apply-templates select="entity"/>
		<xsl:text>
}
</xsl:text>
	</xsl:template>
	<xsl:template match="entity">
		<xsl:text>
	/// &lt;summary&gt;
	/// </xsl:text>
		<xsl:value-of select="@name"/>
		<xsl:text> is a DAL calss that represents </xsl:text>
		<xsl:value-of select="@description"/>
		<xsl:text>. </xsl:text>
		<xsl:text>
	/// &lt;/summary&gt;
	public class </xsl:text>
		<xsl:value-of select="@name"/>
		<xsl:text>
	{</xsl:text>
		<xsl:text>
		/// &lt;summary&gt;
        /// Method to get recoders with condition
        /// &lt;/summary&gt;    	 
        public IList&lt;</xsl:text>
        <xsl:value-of select="@name"/>
        <xsl:text>Info&gt; GetList(string strWhere)
        {

            IList&lt;</xsl:text>
            <xsl:value-of select="@name"/>
            <xsl:text>Info&gt; list = new List&lt;</xsl:text>
            <xsl:value-of select="@name"/>
            <xsl:text>Info&gt;();

            StringBuilder strSql = new StringBuilder();
            strSql.Append("SELECT </xsl:text>
            <xsl:for-each select="./columns/property">
				<xsl:text>[</xsl:text>
				<xsl:value-of select="@name"/>
				<xsl:text>]</xsl:text>
				<xsl:if test="position()!=last()">
					<xsl:text>, </xsl:text>
				</xsl:if>
			</xsl:for-each><xsl:text> ");
            strSql.Append(" FROM [</xsl:text>
            <xsl:value-of select="@name"/>] ");
            <xsl:text>
            if (strWhere.Trim() != "")
            {
                strSql.Append(" WHERE " + strWhere);
            }

            using (SqlDataReader sdr = DbHelperSQL.ExecuteReader(strSql.ToString()))
            {
                while (sdr.Read())
                {
                    </xsl:text>
                    <xsl:value-of select="@name"/>Info<xsl:text> item = new </xsl:text>
                    <xsl:value-of select="@name"/><xsl:text>Info(</xsl:text>
                <xsl:for-each select="./columns/property">
					<xsl:text>sdr.</xsl:text>
					<xsl:value-of select="@getMethod"/>
					<xsl:text>(</xsl:text>	
					<xsl:number value="position()-1" format="1"/>
					<xsl:text>)</xsl:text>
					<xsl:if test="position()!=last()">
						<xsl:text>, </xsl:text>
					</xsl:if>					
				</xsl:for-each><xsl:text>);
                    list.Add(item);
                }
            }
            return list;
        }
        </xsl:text>
        <xsl:text>
		/// &lt;summary&gt;
        /// Method to get one recoder by primary key
        /// &lt;/summary&gt;    	 
        public </xsl:text><xsl:value-of select="@name"/>Info GetModel<xsl:text>(int Id)
        {
			//Set up a return value</xsl:text>
			<xsl:text>
			</xsl:text>
            <xsl:value-of select="@name"/>Info model = null;<xsl:text>

            StringBuilder strSql = new StringBuilder();
            strSql.Append("SELECT </xsl:text>
            <xsl:for-each select="./columns/property">
				<xsl:text>[</xsl:text>
				<xsl:value-of select="@name"/>
				<xsl:text>]</xsl:text>
				<xsl:if test="position()!=last()">
					<xsl:text>, </xsl:text>
				</xsl:if>
			</xsl:for-each><xsl:text> ");
            strSql.Append(" FROM [</xsl:text>
            <xsl:value-of select="@name"/>] ");
            strSql.Append(" WHERE [<xsl:for-each select="./primaryKey/column">
            	<xsl:value-of select="@columnName"/>
          	</xsl:for-each>]=" + Id.ToString());
            <xsl:text>
            using (SqlDataReader sdr = DbHelperSQL.ExecuteReader(strSql.ToString()))
            {
                if (sdr.Read())
                    model = new </xsl:text>
                    <xsl:value-of select="@name"/><xsl:text>Info(</xsl:text>
                <xsl:for-each select="./columns/property">
					<xsl:text>sdr.</xsl:text>
					<xsl:value-of select="@getMethod"/>
					<xsl:text>(</xsl:text>	
					<xsl:number value="position()-1" format="1"/>
					<xsl:text>)</xsl:text>
					<xsl:if test="position()!=last()">
						<xsl:text>, </xsl:text>
					</xsl:if>					
				</xsl:for-each><xsl:text>);
				else
                    model = new </xsl:text>
                    <xsl:value-of select="@name"/><xsl:text>Info();                
            }
            return model;
        }
        </xsl:text>
        /// &lt;summary&gt;
        /// Add one record
        /// &lt;/summary&gt;
        public int Add(<xsl:value-of select="@name"/>Info model)
        {
            StringBuilder strSql = new StringBuilder();
            strSql.Append("INSERT INTO [<xsl:value-of select="@name"/>](");
            strSql.Append("<xsl:for-each select="./columns/property">
								<xsl:text>[</xsl:text>
								<xsl:value-of select="@name"/>
								<xsl:text>]</xsl:text>	
								<xsl:if test="position()!=last()">
									<xsl:text>,</xsl:text>
								</xsl:if>					
							</xsl:for-each>");
            strSql.Append(")");
            strSql.Append(" VALUES (");
            <xsl:for-each select="./columns/property">
            	<xsl:if test="@identity!='True'">
		            <xsl:text>strSql.Append("</xsl:text>
		            <xsl:if test="@pattern='Yes'">
		            	<xsl:text>'</xsl:text>
		            </xsl:if>
					<xsl:text>" + </xsl:text>
					<xsl:if test="@pattern='Boolean'">
		            	<xsl:text>(</xsl:text>
		            </xsl:if>
		            <xsl:text>model.</xsl:text>
					<xsl:value-of select="@name"/>
					<xsl:if test="@pattern='Boolean'">
		            	<xsl:text> == true ? "1" : "0")</xsl:text>
		            </xsl:if>
					<xsl:text> + "</xsl:text>
					<xsl:if test="@pattern='Yes'">
		            	<xsl:text>'</xsl:text>
		            </xsl:if>
		            <xsl:if test="position()!=last()">
						<xsl:text>,</xsl:text>
					</xsl:if>
					<xsl:text>");
			</xsl:text>
				</xsl:if>
			</xsl:for-each>strSql.Append(")");
            strSql.Append(";SELECT @@IDENTITY");
            object obj = DbHelperSQL.GetSingle(strSql.ToString());
            if (obj == null)
            {
                return 1;
            }
            else
            {
                return Convert.ToInt32(obj);
            }
        }
        /// &lt;summary&gt;
        /// Update one record
        /// &lt;/summary&gt;
        public void Update(<xsl:value-of select="@name"/>Info model)
        {
            StringBuilder strSql = new StringBuilder();
            strSql.Append("UPDATE [<xsl:value-of select="@name"/>] SET ");
            <xsl:for-each select="./columns/property">
            	<xsl:if test="@identity!='True'">
		            <xsl:text>strSql.Append("[</xsl:text>
		            <xsl:value-of select="@name"/>
					<xsl:text>]=</xsl:text>
					<xsl:if test="@pattern='Yes'">
		            	<xsl:text>'</xsl:text>
		            </xsl:if>
		            <xsl:text>" + </xsl:text>
					<xsl:if test="@pattern='Boolean'">
		            	<xsl:text>(</xsl:text>
		            </xsl:if>
		            <xsl:text>model.</xsl:text>		            
					<xsl:value-of select="@name"/>
					<xsl:if test="@pattern='Boolean'">
		            	<xsl:text> == true ? "1" : "0")</xsl:text>
		            </xsl:if>
					<xsl:text> + "</xsl:text>
					<xsl:if test="@pattern='Yes'">
		            	<xsl:text>'</xsl:text>
		            </xsl:if>
		            <xsl:if test="position()!=last()">
						<xsl:text>,</xsl:text>
					</xsl:if>
					<xsl:text>");
			</xsl:text>
				</xsl:if>
			</xsl:for-each>strSql.Append(" WHERE [<xsl:for-each select="./primaryKey/column">
            	<xsl:value-of select="@columnName"/>]=" + model.<xsl:value-of select="@columnName"/> + ""</xsl:for-each>);
            DbHelperSQL.ExecuteSql(strSql.ToString());
        }
        
        /// &lt;summary&gt;
		/// Delete record by primary key
		/// &lt;/summary&gt;
        public void Delete(int Id)
        {
            StringBuilder strSql = new StringBuilder();
            strSql.Append("DELETE FROM [<xsl:value-of select="@name"/>] WHERE [<xsl:for-each select="./primaryKey/column">
            	<xsl:value-of select="@columnName"/>
            </xsl:for-each>]=" + Id.ToString());
            DbHelperSQL.ExecuteSql(strSql.ToString());
        }
        
        /// &lt;summary&gt;
		/// Check exist by primary key
		/// &lt;/summary&gt;
        public bool IsExist(int Id)
        {
            StringBuilder strSql = new StringBuilder();
            strSql.Append("SELECT COUNT(1) FROM [<xsl:value-of select="@name"/>] WHERE [<xsl:for-each select="./primaryKey/column">
            <xsl:value-of select="@columnName"/></xsl:for-each>]=" + Id.ToString() + "");
            return DbHelperSQL.Exists(strSql.ToString());
        }
	}
	</xsl:template>
</xsl:stylesheet>
