SELECT
 T.TABLE_NAME,
 COALESCE( CU.CONSTRAINT_NAME , '(no primary key)') 
    AS PRIMARY_KEY_NAME,
 CU.COLUMN_NAME 
FROM INFORMATION_SCHEMA.TABLES AS T
LEFT JOIN INFORMATION_SCHEMA.TABLE_CONSTRAINTS AS TC
 ON TC.TABLE_CATALOG = T.TABLE_CATALOG
 AND TC.TABLE_SCHEMA = T.TABLE_SCHEMA
 AND TC.TABLE_NAME = T.TABLE_NAME
 AND TC.CONSTRAINT_TYPE = 'PRIMARY KEY'
LEFT JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE AS CU
 ON CU.CONSTRAINT_CATALOG = TC.CONSTRAINT_CATALOG
 AND CU.CONSTRAINT_SCHEMA = TC.CONSTRAINT_SCHEMA
 AND CU.CONSTRAINT_NAME = TC.CONSTRAINT_NAME
WHERE
 T.TABLE_TYPE = 'BASE TABLE'
ORDER BY
 T.TABLE_NAME,
 CU.ORDINAL_POSITION