SELECT
        INFORMATION_SCHEMA.COLUMNS.ORDINAL_POSITION,
        INFORMATION_SCHEMA.COLUMNS.COLUMN_NAME,
        INFORMATION_SCHEMA.COLUMNS.DATA_TYPE,
        COL_LENGTH('#TableName#', INFORMATION_SCHEMA.COLUMNS.COLUMN_NAME) AS COLUMN_LENGTH,
        INFORMATION_SCHEMA.COLUMNS.NUMERIC_SCALE,
        COLUMNPROPERTY(OBJECT_ID('#TableName#'), INFORMATION_SCHEMA.COLUMNS.COLUMN_NAME, 'IsIdentity') AS IS_IDENTITY,
        INFORMATION_SCHEMA.COLUMNS.IS_NULLABLE,
        INFORMATION_SCHEMA.COLUMNS.COLUMN_DEFAULT
FROM
	INFORMATION_SCHEMA.COLUMNS
WHERE
	INFORMATION_SCHEMA.COLUMNS.TABLE_NAME = '#TableName#'